### Bismillah

###

### Customer Churn Prediction & Revenue Analysis Using Machine Learning

## 🧠 What this project does

#### We predict which customers will leave the company (churn)
#### And find why they are leaving, using data

In [3]:
import numpy  as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
%matplotlib inline
plt.show()

In [4]:
df = pd.read_csv("customer_data.csv")

In [5]:
df

,customer_id,age,gender,country,tenure_months,monthly_charges,support_tickets,contract_type,last_login_days,is_premium,churn
0,1,25,Male,India,2,50,4,Monthly,45,0,1
1,2,32,Female,USA,24,70,1,Yearly,5,1,0
2,3,40,Male,UK,12,90,3,Monthly,20,0,0
3,4,29,Female,India,1,40,5,Monthly,60,0,1
4,5,35,Male,Canada,36,110,0,Yearly,2,1,0
5,6,22,Female,India,3,45,4,Monthly,50,0,1
6,7,45,Male,USA,48,100,1,Yearly,3,1,0
7,8,31,Female,UK,6,65,2,Monthly,25,0,0
8,9,27,Male,India,2,55,5,Monthly,40,0,1
9,10,38,Female,Canada,30,95,1,Yearly,4,1,0

# 🧾 DATA DICTIONARY – Customer Churn Dataset

| Column Name         | Data Type     | Description                                   | Example                 |
| ------------------- | ------------- | --------------------------------------------- | ----------------------- |
| **customer_id**     | Integer       | Unique ID for each customer                   | 1012                    |
| **age**             | Integer       | Age of the customer in years                  | 28                      |
| **gender**          | Categorical   | Gender of the customer                        | Male / Female           |
| **country**         | Categorical   | Country where customer lives                  | India, USA              |
| **tenure_months**   | Integer       | Number of months customer stayed with company | 12                      |
| **monthly_charges** | Integer       | Monthly subscription cost (USD)               | 49                      |
| **support_tickets** | Integer       | Number of customer support issues raised      | 3                       |
| **contract_type**   | Categorical   | Subscription contract type                    | Monthly / Yearly        |
| **last_login_days** | Integer       | Days since customer last logged in            | 15                      |
| **is_premium**      | Integer (0/1) | Whether customer has premium plan             | 1 = Yes, 0 = No         |
| **churn**           | Integer (0/1) | Target variable – customer left or not        | 1 = Churned, 0 = Active |

In [7]:
df.head()

,customer_id,age,gender,country,tenure_months,monthly_charges,support_tickets,contract_type,last_login_days,is_premium,churn
0,1,25,Male,India,2,50,4,Monthly,45,0,1
1,2,32,Female,USA,24,70,1,Yearly,5,1,0
2,3,40,Male,UK,12,90,3,Monthly,20,0,0
3,4,29,Female,India,1,40,5,Monthly,60,0,1
4,5,35,Male,Canada,36,110,0,Yearly,2,1,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      10 non-null     int64
 1   age              10 non-null     int64
 2   gender           10 non-null     object
 3   country          10 non-null     object
 4   tenure_months    10 non-null     int64
 5   monthly_charges  10 non-null     int64
 6   support_tickets  10 non-null     int64
 7   contract_type    10 non-null     object
 8   last_login_days  10 non-null     int64
 9   is_premium       10 non-null     int64
 10  churn            10 non-null     int64
dtypes: int64(8), object(3)
memory usage: 1012.0+ bytes

## Simple Analysis

In [9]:
df['churn'].value_counts()

churn
0    6
1    4
Name: count, dtype: int64

In [10]:
df.groupby('churn')['monthly_charges'].mean()

churn
0    88.333333
1    47.500000
Name: monthly_charges, dtype: float64

## Convert Text to Numbers

In [14]:
df['gender'] = df['gender'].map({'Male':0, 'Female':1})
df['contract_type'] = df['contract_type'].map({'Monthly':0, 'Yearly':1})
df['country'] = df['country'].map({'India':0, 'USA':1, 'UK':2, 'Canada':3})

In [15]:
df['gender']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: gender, dtype: float64

In [16]:
df['contract_type']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: contract_type, dtype: float64

In [17]:
df['country']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: country, dtype: float64

##  Split X and y

In [18]:
X = df.drop(['customer_id','churn'], axis=1)
y = df['churn']

In [20]:
X

,age,gender,country,tenure_months,monthly_charges,support_tickets,contract_type,last_login_days,is_premium
0,25,NaN,NaN,2,50,4,NaN,45,0
1,32,NaN,NaN,24,70,1,NaN,5,1
2,40,NaN,NaN,12,90,3,NaN,20,0
3,29,NaN,NaN,1,40,5,NaN,60,0
4,35,NaN,NaN,36,110,0,NaN,2,1
5,22,NaN,NaN,3,45,4,NaN,50,0
6,45,NaN,NaN,48,100,1,NaN,3,1
7,31,NaN,NaN,6,65,2,NaN,25,0
8,27,NaN,NaN,2,55,5,NaN,40,0
9,38,NaN,NaN,30,95,1,NaN,4,1

In [21]:
y

0    1
1    0
2    0
3    1
4    0
5    1
6    0
7    0
8    1
9    0
Name: churn, dtype: int64

In [29]:
X.isna().sum()

age                 0
gender             10
country            10
tenure_months       0
monthly_charges     0
support_tickets     0
contract_type      10
last_login_days     0
is_premium          0
dtype: int64

In [30]:
X = X.fillna(0)

In [31]:
X

,age,gender,country,tenure_months,monthly_charges,support_tickets,contract_type,last_login_days,is_premium
0,25,0.0,0.0,2,50,4,0.0,45,0
1,32,0.0,0.0,24,70,1,0.0,5,1
2,40,0.0,0.0,12,90,3,0.0,20,0
3,29,0.0,0.0,1,40,5,0.0,60,0
4,35,0.0,0.0,36,110,0,0.0,2,1
5,22,0.0,0.0,3,45,4,0.0,50,0
6,45,0.0,0.0,48,100,1,0.0,3,1
7,31,0.0,0.0,6,65,2,0.0,25,0
8,27,0.0,0.0,2,55,5,0.0,40,0
9,38,0.0,0.0,30,95,1,0.0,4,1

In [32]:
X = pd.get_dummies(X, drop_first=True)

In [33]:
X

,age,gender,country,tenure_months,monthly_charges,support_tickets,contract_type,last_login_days,is_premium
0,25,0.0,0.0,2,50,4,0.0,45,0
1,32,0.0,0.0,24,70,1,0.0,5,1
2,40,0.0,0.0,12,90,3,0.0,20,0
3,29,0.0,0.0,1,40,5,0.0,60,0
4,35,0.0,0.0,36,110,0,0.0,2,1
5,22,0.0,0.0,3,45,4,0.0,50,0
6,45,0.0,0.0,48,100,1,0.0,3,1
7,31,0.0,0.0,6,65,2,0.0,25,0
8,27,0.0,0.0,2,55,5,0.0,40,0
9,38,0.0,0.0,30,95,1,0.0,4,1

In [34]:
X = X.fillna(0)

In [35]:
X

,age,gender,country,tenure_months,monthly_charges,support_tickets,contract_type,last_login_days,is_premium
0,25,0.0,0.0,2,50,4,0.0,45,0
1,32,0.0,0.0,24,70,1,0.0,5,1
2,40,0.0,0.0,12,90,3,0.0,20,0
3,29,0.0,0.0,1,40,5,0.0,60,0
4,35,0.0,0.0,36,110,0,0.0,2,1
5,22,0.0,0.0,3,45,4,0.0,50,0
6,45,0.0,0.0,48,100,1,0.0,3,1
7,31,0.0,0.0,6,65,2,0.0,25,0
8,27,0.0,0.0,2,55,5,0.0,40,0
9,38,0.0,0.0,30,95,1,0.0,4,1

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [37]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

LogisticRegression(max_iter=1000)

In [39]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3